# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-21 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TOURISM', 'Tourism'), ('HOTELS', 'Hotels'), ('BED_BREAKFEST', 'Bed and Breakfast'), ('VACATION_RENTALS', 'Vacation Rentals'), ('VACATION_PACKAGES', 'Vacation Packages'), ('FLIGHTS', 'Flights'), ('RESTAURANTS', 'Restaurants'), ('THINGS_TO_DO', 'Things to Do'), ('TRAVEL_FOURM', 'Travel Forum'), ('TRAVEL_GUIDE', 'Travel Guide')], default='TOURISM', max_length=2)),
                ('url', models.URLField()),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.Destination')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
                ('website', models.CharField(blank=True, max_length=255)),
                ('features', models.CharField(blank=True, max_length=255)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('price_from', models.CharField(blank=True, max_length=255)),
                ('price_to', models.CharField(blank=True, max_length=255)),
                ('lat', models.CharField(blank=True, max_length=255)),
                ('lng', models.CharField(blank=True, max_length=255)),
                ('about_ar', models.TextField(blank=True)),
                ('title_ar', models.TextField(blank=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.Link')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=125)),
                ('time_from', models.CharField(blank=True, max_length=125)),
                ('time_to', models.CharField(blank=True, max_length=125)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.Listing')),
            ],
        ),
    ]
