# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripadvisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='link',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='listing',
            options={'verbose_name': 'Listing', 'verbose_name_plural': 'Listings'},
        ),
        migrations.AlterModelOptions(
            name='workinghours',
            options={'verbose_name': 'WorkingHour', 'verbose_name_plural': 'WorkingHours'},
        ),
        migrations.AddField(
            model_name='link',
            name='items_count',
            field=models.IntegerField(default=10),
        ),
    ]
