# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripadvisor', '0003_missing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='source',
            field=models.CharField(choices=[('TRIPADVISOR', 'tripadvisor'), ('BOOKING', 'Booking'), ('OTHER', 'Other')], default='TRIPADVISOR', max_length=200),
        ),
        migrations.AlterField(
            model_name='link',
            name='category',
            field=models.CharField(choices=[('NATURE_PARKS', 'Nature & Parks'), ('MUSEUMS', 'Museums'), ('SHOPPING', 'Shopping'), ('ZOOS_AQUARIUMS', 'Zoos & Aquariums'), ('FOOD_DRINK', 'Food & Drink'), ('WATER_AMUSEMENT_PARKS', 'Water & Amusement Parks'), ('RESTAURANTS', 'Restaurants')], default='NATURE_PARKS', max_length=200),
        ),
    ]
