# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripadvisor', '0004_listing_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='features_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='source',
            field=models.CharField(choices=[('TRIPADVISOR', 'tripadvisor'), ('BOOKING', 'Booking')], default='TRIPADVISOR', max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='about_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lng',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
